"""Application boundary DTOs for workspace reading."""

from fabrica.features.workspace_reading.application.dtos.read_files import (
    DEFAULT_MAX_FILES_PER_CALL,
    DEFAULT_MAX_IMAGE_BYTES,
    DEFAULT_MAX_LINE_CHARS,
    DEFAULT_MAX_METADATA_SCAN_LINES,
    DEFAULT_MAX_PARALLEL_READS,
    DEFAULT_MAX_READ_LINES,
    DEFAULT_MAX_READ_OUTPUT_CHARS,
    DEFAULT_MAX_RETRIES,
    DEFAULT_MAX_TEXT_FILE_BYTES,
    DEFAULT_PER_FILE_DEADLINE_SECONDS,
    DEFAULT_TOOL_DEADLINE_SECONDS,
    ImageContent,
    ImageFileResult,
    ReadFileError,
    ReadFileErrorCode,
    ReadFileFailure,
    ReadFileRequest,
    ReadFileResult,
    ReadFilesCommand,
    ReadFilesLimits,
    ReadFilesResult,
    ReadFileType,
    SafeReadMetadataValue,
    TextFileResult,
)

__all__ = [
    "DEFAULT_MAX_FILES_PER_CALL",
    "DEFAULT_MAX_IMAGE_BYTES",
    "DEFAULT_MAX_LINE_CHARS",
    "DEFAULT_MAX_METADATA_SCAN_LINES",
    "DEFAULT_MAX_PARALLEL_READS",
    "DEFAULT_MAX_READ_LINES",
    "DEFAULT_MAX_READ_OUTPUT_CHARS",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_MAX_TEXT_FILE_BYTES",
    "DEFAULT_PER_FILE_DEADLINE_SECONDS",
    "DEFAULT_TOOL_DEADLINE_SECONDS",
    "ImageContent",
    "ImageFileResult",
    "ReadFileError",
    "ReadFileErrorCode",
    "ReadFileFailure",
    "ReadFileRequest",
    "ReadFileResult",
    "ReadFileType",
    "ReadFilesCommand",
    "ReadFilesLimits",
    "ReadFilesResult",
    "SafeReadMetadataValue",
    "TextFileResult",
]
