"""Application boundary DTOs for workspace source discovery."""

from fabrica.features.workspace_searching.application.dtos.search_codebase import (
    DEFAULT_CONTEXT_LINES,
    DEFAULT_MAX_LINE_CHARS,
    DEFAULT_MAX_OUTPUT_PER_QUERY,
    DEFAULT_MAX_OUTPUT_PER_TOOL_CALL,
    DEFAULT_MAX_PARALLEL_SEARCHES,
    DEFAULT_MAX_QUERIES_PER_CALL,
    DEFAULT_MAX_RESULTS_PER_QUERY,
    DEFAULT_MAX_RETRIES,
    DEFAULT_MAX_SEARCH_FILE_BYTES,
    DEFAULT_PER_QUERY_TIMEOUT_SECONDS,
    DEFAULT_TOOL_TIMEOUT_SECONDS,
    SafeSearchMetadataValue,
    SearchCodebaseCommand,
    SearchCodebaseResult,
    SearchContextLine,
    SearchError,
    SearchErrorCode,
    SearchLimits,
    SearchMatch,
    SearchQuery,
    SearchQueryFailure,
    SearchQueryResult,
    SearchQuerySuccess,
)
from fabrica.features.workspace_searching.application.dtos.search_location import SearchLocation

__all__ = [
    "DEFAULT_CONTEXT_LINES",
    "DEFAULT_MAX_LINE_CHARS",
    "DEFAULT_MAX_OUTPUT_PER_QUERY",
    "DEFAULT_MAX_OUTPUT_PER_TOOL_CALL",
    "DEFAULT_MAX_PARALLEL_SEARCHES",
    "DEFAULT_MAX_QUERIES_PER_CALL",
    "DEFAULT_MAX_RESULTS_PER_QUERY",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_MAX_SEARCH_FILE_BYTES",
    "DEFAULT_PER_QUERY_TIMEOUT_SECONDS",
    "DEFAULT_TOOL_TIMEOUT_SECONDS",
    "SafeSearchMetadataValue",
    "SearchCodebaseCommand",
    "SearchCodebaseResult",
    "SearchContextLine",
    "SearchError",
    "SearchErrorCode",
    "SearchLimits",
    "SearchLocation",
    "SearchMatch",
    "SearchQuery",
    "SearchQueryFailure",
    "SearchQueryResult",
    "SearchQuerySuccess",
]
