"""Safe adapter-local error messages for read-only git context failures."""

DECODE_ERROR_MESSAGE = "read-only git context output could not be decoded as UTF-8"
GIT_CONTEXT_FAILED_MESSAGE = "read-only git context command failed"
GIT_CONTEXT_START_FAILED_MESSAGE = "read-only git context command failed to start"
GIT_CONTEXT_TIMED_OUT_MESSAGE = "read-only git context command timed out"
GIT_UNAVAILABLE_MESSAGE = "git executable is unavailable"
INVALID_COMMIT_MESSAGE = "requested git commit could not be validated"
INVALID_REF_MESSAGE = "requested git ref could not be validated"
NO_MATCHING_CHANGES_MESSAGE = "requested git context path has no matching changes"
NOT_REPOSITORY_MESSAGE = "current directory is not inside a git repository"
OVERSIZED_OUTPUT_MESSAGE = "read-only git context output exceeds the configured bound"
UNSAFE_ARGUMENT_MESSAGE = "requested read-only git context argument is invalid"
UNSUPPORTED_OUTPUT_MESSAGE = "read-only git context output is not supported"
