"""Application boundary DTOs for public web-content retrieval."""

from fabrica.features.web_content_fetching.application.dtos.fetch_web_content import (
    DEFAULT_MAX_BATCH_CONTENT_CHARS,
    DEFAULT_MAX_CONTENT_CHARS,
    DEFAULT_MAX_PARALLEL_FETCHES,
    DEFAULT_MAX_REDIRECTS,
    DEFAULT_MAX_REQUESTS_PER_CALL,
    DEFAULT_MAX_RESPONSE_BYTES,
    DEFAULT_MAX_RETRIES,
    DEFAULT_PER_REQUEST_TIMEOUT_SECONDS,
    TRUST_UNTRUSTED_WEB_CONTENT,
    FetchAttemptFailure,
    FetchAttemptOutcome,
    FetchAttemptSuccess,
    FetchContentFormat,
    FetchError,
    FetchErrorCode,
    FetchFailure,
    FetchRedirect,
    FetchResult,
    FetchSuccess,
    FetchWebContentCommand,
    FetchWebContentLimits,
    FetchWebContentRequest,
    FetchWebContentResult,
    ProcessedWebContent,
    SafeFetchMetadataValue,
)

__all__ = [
    "DEFAULT_MAX_BATCH_CONTENT_CHARS",
    "DEFAULT_MAX_CONTENT_CHARS",
    "DEFAULT_MAX_PARALLEL_FETCHES",
    "DEFAULT_MAX_REDIRECTS",
    "DEFAULT_MAX_REQUESTS_PER_CALL",
    "DEFAULT_MAX_RESPONSE_BYTES",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_PER_REQUEST_TIMEOUT_SECONDS",
    "TRUST_UNTRUSTED_WEB_CONTENT",
    "FetchAttemptFailure",
    "FetchAttemptOutcome",
    "FetchAttemptSuccess",
    "FetchContentFormat",
    "FetchError",
    "FetchErrorCode",
    "FetchFailure",
    "FetchRedirect",
    "FetchResult",
    "FetchSuccess",
    "FetchWebContentCommand",
    "FetchWebContentLimits",
    "FetchWebContentRequest",
    "FetchWebContentResult",
    "ProcessedWebContent",
    "SafeFetchMetadataValue",
]
